// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID          uuid.UUID     `json:"id"`
	MessageID   uuid.NullUUID `json:"message_id"`
	Filename    string        `json:"filename"`
	ContentType string        `json:"content_type"`
	Size        int32         `json:"size"`
	ObjectKey   string        `json:"object_key"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Domain struct {
	ID         uuid.UUID    `json:"id"`
	DomainName string       `json:"domain_name"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Inbox struct {
	ID             uuid.UUID      `json:"id"`
	Address        string         `json:"address"`
	DomainID       uuid.NullUUID  `json:"domain_id"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	Status         sql.NullString `json:"status"`
}

type Message struct {
	ID         uuid.UUID      `json:"id"`
	InboxID    uuid.NullUUID  `json:"inbox_id"`
	Sender     string         `json:"sender"`
	Recipient  string         `json:"recipient"`
	Subject    sql.NullString `json:"subject"`
	TextBody   sql.NullString `json:"text_body"`
	HtmlBody   sql.NullString `json:"html_body"`
	RawHeaders sql.NullString `json:"raw_headers"`
	SpamScore  sql.NullString `json:"spam_score"`
	ReceivedAt sql.NullTime   `json:"received_at"`
}
