// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (message_id, filename, content_type, size, object_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, filename, content_type, size, object_key, created_at
`

type CreateAttachmentParams struct {
	MessageID   uuid.NullUUID `json:"message_id"`
	Filename    string        `json:"filename"`
	ContentType string        `json:"content_type"`
	Size        int32         `json:"size"`
	ObjectKey   string        `json:"object_key"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.MessageID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.ObjectKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (domain_name)
VALUES ($1)
RETURNING id, domain_name, created_at
`

func (q *Queries) CreateDomain(ctx context.Context, domainName string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain, domainName)
	var i Domain
	err := row.Scan(&i.ID, &i.DomainName, &i.CreatedAt)
	return i, err
}

const createInbox = `-- name: CreateInbox :one
INSERT INTO inboxes (address, domain_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, address, domain_id, expires_at, created_at, last_accessed_at, status
`

type CreateInboxParams struct {
	Address   string        `json:"address"`
	DomainID  uuid.NullUUID `json:"domain_id"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) CreateInbox(ctx context.Context, arg CreateInboxParams) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, createInbox, arg.Address, arg.DomainID, arg.ExpiresAt)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.DomainID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Status,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (inbox_id, sender, recipient, subject, text_body, html_body, raw_headers, spam_score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, inbox_id, sender, recipient, subject, text_body, html_body, raw_headers, spam_score, received_at
`

type CreateMessageParams struct {
	InboxID    uuid.NullUUID  `json:"inbox_id"`
	Sender     string         `json:"sender"`
	Recipient  string         `json:"recipient"`
	Subject    sql.NullString `json:"subject"`
	TextBody   sql.NullString `json:"text_body"`
	HtmlBody   sql.NullString `json:"html_body"`
	RawHeaders sql.NullString `json:"raw_headers"`
	SpamScore  sql.NullString `json:"spam_score"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.InboxID,
		arg.Sender,
		arg.Recipient,
		arg.Subject,
		arg.TextBody,
		arg.HtmlBody,
		arg.RawHeaders,
		arg.SpamScore,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.InboxID,
		&i.Sender,
		&i.Recipient,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.RawHeaders,
		&i.SpamScore,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteExpiredInboxes = `-- name: DeleteExpiredInboxes :many
DELETE FROM inboxes
WHERE expires_at < NOW()
RETURNING id, address, domain_id, expires_at, created_at, last_accessed_at, status
`

func (q *Queries) DeleteExpiredInboxes(ctx context.Context) ([]Inbox, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredInboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbox{}
	for rows.Next() {
		var i Inbox
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.DomainID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastAccessedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInbox = `-- name: DeleteInbox :exec
DELETE FROM inboxes
WHERE id = $1
`

func (q *Queries) DeleteInbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInbox, id)
	return err
}

const deleteOldMessages = `-- name: DeleteOldMessages :many
DELETE FROM messages
WHERE received_at < NOW() - INTERVAL '24 hours'
RETURNING id, inbox_id, sender, recipient, subject, text_body, html_body, raw_headers, spam_score, received_at
`

func (q *Queries) DeleteOldMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, deleteOldMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.InboxID,
			&i.Sender,
			&i.Recipient,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.RawHeaders,
			&i.SpamScore,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendInbox = `-- name: ExtendInbox :one
UPDATE inboxes
SET expires_at = $2
WHERE id = $1
RETURNING id, address, domain_id, expires_at, created_at, last_accessed_at, status
`

type ExtendInboxParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ExtendInbox(ctx context.Context, arg ExtendInboxParams) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, extendInbox, arg.ID, arg.ExpiresAt)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.DomainID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Status,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, message_id, filename, content_type, size, object_key, created_at FROM attachments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, domain_name, created_at FROM domains
WHERE domain_name = $1 LIMIT 1
`

func (q *Queries) GetDomainByName(ctx context.Context, domainName string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomainByName, domainName)
	var i Domain
	err := row.Scan(&i.ID, &i.DomainName, &i.CreatedAt)
	return i, err
}

const getInbox = `-- name: GetInbox :one
SELECT id, address, domain_id, expires_at, created_at, last_accessed_at, status FROM inboxes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInbox(ctx context.Context, id uuid.UUID) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, getInbox, id)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.DomainID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Status,
	)
	return i, err
}

const getInboxByAddress = `-- name: GetInboxByAddress :one
SELECT id, address, domain_id, expires_at, created_at, last_accessed_at, status FROM inboxes
WHERE address = $1 LIMIT 1
`

func (q *Queries) GetInboxByAddress(ctx context.Context, address string) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, getInboxByAddress, address)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.DomainID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastAccessedAt,
		&i.Status,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, inbox_id, sender, recipient, subject, text_body, html_body, raw_headers, spam_score, received_at FROM messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.InboxID,
		&i.Sender,
		&i.Recipient,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.RawHeaders,
		&i.SpamScore,
		&i.ReceivedAt,
	)
	return i, err
}

const listAttachmentsForMessage = `-- name: ListAttachmentsForMessage :many
SELECT id, message_id, filename, content_type, size, object_key, created_at FROM attachments
WHERE message_id = $1
`

func (q *Queries) ListAttachmentsForMessage(ctx context.Context, messageID uuid.NullUUID) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, domain_name, created_at FROM domains
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(&i.ID, &i.DomainName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesForInbox = `-- name: ListMessagesForInbox :many
SELECT id, inbox_id, sender, recipient, subject, text_body, html_body, raw_headers, spam_score, received_at FROM messages
WHERE inbox_id = $1
ORDER BY received_at DESC
`

func (q *Queries) ListMessagesForInbox(ctx context.Context, inboxID uuid.NullUUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesForInbox, inboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.InboxID,
			&i.Sender,
			&i.Recipient,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.RawHeaders,
			&i.SpamScore,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInboxLastAccessed = `-- name: UpdateInboxLastAccessed :exec
UPDATE inboxes
SET last_accessed_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateInboxLastAccessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateInboxLastAccessed, id)
	return err
}
