// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateDomain(ctx context.Context, domainName string) (Domain, error)
	CreateInbox(ctx context.Context, arg CreateInboxParams) (Inbox, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredInboxes(ctx context.Context) ([]Inbox, error)
	DeleteInbox(ctx context.Context, id uuid.UUID) error
	DeleteOldMessages(ctx context.Context) ([]Message, error)
	DeleteSession(ctx context.Context, refreshToken string) error
	ExtendInbox(ctx context.Context, arg ExtendInboxParams) (Inbox, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetDomainByName(ctx context.Context, domainName string) (Domain, error)
	GetInbox(ctx context.Context, id uuid.UUID) (Inbox, error)
	GetInboxByAddress(ctx context.Context, address string) (Inbox, error)
	GetMessage(ctx context.Context, id uuid.UUID) (Message, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetSubscriptionByUserId(ctx context.Context, userID uuid.NullUUID) (Subscription, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	ListAttachmentsForMessage(ctx context.Context, messageID uuid.NullUUID) ([]Attachment, error)
	ListDomains(ctx context.Context) ([]Domain, error)
	ListMessagesForInbox(ctx context.Context, inboxID uuid.NullUUID) ([]Message, error)
	UpdateInboxLastAccessed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
